export type BackendRole =
  | 'CUSTOMER'
  | 'TELLER'
  | 'MANAGER'
  | 'FRAUD_ANALYST'
  | 'ADMIN'
  | 'CRYPTOCURRENCY_USER'
  | 'CRYPTO_INVESTOR'
  | 'CRYPTO_TRADER'
  | 'SPOT_TRADING_USER'
  | 'FUTURES_TRADING_USER'
  | 'P2P_CRYPTO_USER'
  | 'NFT_USER'
  | 'DEFI_USER'
  | 'STAKING_USER'
  | 'YIELD_FARMING_USER'
  | 'CRYPTO_WALLET_USER'
  | 'CRYPTO_PAYMENT_USER'
  | 'TOKEN_HOLDER'
  | 'DAO_MEMBER'
  | 'WEB3_USER'
  | 'BLOCKCHAIN_GAMER'
  | 'MINING_USER'
  | 'VALIDATOR_NODE_OPERATOR'
  | 'AIRDROP_PARTICIPANT'
  | 'STABLECOIN_USER'
  | 'CROSS_BORDER_CRYPTO_TRANSFER_USER'
  | 'INSTITUTIONAL_CRYPTO_INVESTOR'
  | 'CRYPTO_MERCHANT'
  | 'OTC_TRADING_USER'
  | 'CRYPTO_LENDING_USER'
  | 'CRYPTO_BORROWING_USER'
  | 'CRYPTO_EXCHANGE_USER'
  | 'SMART_CONTRACT_USER'
  | 'METAVERSE_USER'
  | 'CRYPTO_REMITTANCE_USER'
  | 'BLOCKCHAIN_DEVELOPER'
  | 'CUSTODIAL_WALLET_USER'
  | 'NON_CUSTODIAL_WALLET_USER';

export const BACKEND_ROLES: BackendRole[] = [
  'CUSTOMER',
  'TELLER',
  'MANAGER',
  'FRAUD_ANALYST',
  'ADMIN',
  'CRYPTOCURRENCY_USER',
  'CRYPTO_INVESTOR',
  'CRYPTO_TRADER',
  'SPOT_TRADING_USER',
  'FUTURES_TRADING_USER',
  'P2P_CRYPTO_USER',
  'NFT_USER',
  'DEFI_USER',
  'STAKING_USER',
  'YIELD_FARMING_USER',
  'CRYPTO_WALLET_USER',
  'CRYPTO_PAYMENT_USER',
  'TOKEN_HOLDER',
  'DAO_MEMBER',
  'WEB3_USER',
  'BLOCKCHAIN_GAMER',
  'MINING_USER',
  'VALIDATOR_NODE_OPERATOR',
  'AIRDROP_PARTICIPANT',
  'STABLECOIN_USER',
  'CROSS_BORDER_CRYPTO_TRANSFER_USER',
  'INSTITUTIONAL_CRYPTO_INVESTOR',
  'CRYPTO_MERCHANT',
  'OTC_TRADING_USER',
  'CRYPTO_LENDING_USER',
  'CRYPTO_BORROWING_USER',
  'CRYPTO_EXCHANGE_USER',
  'SMART_CONTRACT_USER',
  'METAVERSE_USER',
  'CRYPTO_REMITTANCE_USER',
  'BLOCKCHAIN_DEVELOPER',
  'CUSTODIAL_WALLET_USER',
  'NON_CUSTODIAL_WALLET_USER'
];

export const CRYPTO_ROLES: BackendRole[] = [
  'CRYPTOCURRENCY_USER',
  'CRYPTO_INVESTOR',
  'CRYPTO_TRADER',
  'SPOT_TRADING_USER',
  'FUTURES_TRADING_USER',
  'P2P_CRYPTO_USER',
  'NFT_USER',
  'DEFI_USER',
  'STAKING_USER',
  'YIELD_FARMING_USER',
  'CRYPTO_WALLET_USER',
  'CRYPTO_PAYMENT_USER',
  'TOKEN_HOLDER',
  'DAO_MEMBER',
  'WEB3_USER',
  'BLOCKCHAIN_GAMER',
  'MINING_USER',
  'VALIDATOR_NODE_OPERATOR',
  'AIRDROP_PARTICIPANT',
  'STABLECOIN_USER',
  'CROSS_BORDER_CRYPTO_TRANSFER_USER',
  'INSTITUTIONAL_CRYPTO_INVESTOR',
  'CRYPTO_MERCHANT',
  'OTC_TRADING_USER',
  'CRYPTO_LENDING_USER',
  'CRYPTO_BORROWING_USER',
  'CRYPTO_EXCHANGE_USER',
  'SMART_CONTRACT_USER',
  'METAVERSE_USER',
  'CRYPTO_REMITTANCE_USER',
  'BLOCKCHAIN_DEVELOPER',
  'CUSTODIAL_WALLET_USER',
  'NON_CUSTODIAL_WALLET_USER'
];

export const INVESTMENT_ROLES: BackendRole[] = [
  'CRYPTO_INVESTOR',
  'INSTITUTIONAL_CRYPTO_INVESTOR',
  'CRYPTO_TRADER',
  'SPOT_TRADING_USER',
  'FUTURES_TRADING_USER',
  'OTC_TRADING_USER',
  'TOKEN_HOLDER',
  'DEFI_USER',
  'STAKING_USER',
  'YIELD_FARMING_USER',
  'CRYPTO_LENDING_USER',
  'CRYPTO_BORROWING_USER'
];

export const PAYMENT_ROLES: BackendRole[] = [
  'CRYPTO_MERCHANT',
  'CRYPTO_PAYMENT_USER',
  'STABLECOIN_USER',
  'CROSS_BORDER_CRYPTO_TRANSFER_USER',
  'CRYPTO_REMITTANCE_USER'
];

export const FINTECH_PARTNER_ROLES: BackendRole[] = [
  'BLOCKCHAIN_DEVELOPER',
  'DAO_MEMBER',
  'WEB3_USER',
  'SMART_CONTRACT_USER',
  'VALIDATOR_NODE_OPERATOR',
  'MINING_USER',
  'CUSTODIAL_WALLET_USER',
  'NON_CUSTODIAL_WALLET_USER'
];

export function roleDisplayName(role: BackendRole): string {
  return role
    .toLowerCase()
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export type PersonaKey =
  | 'customer'
  | 'admin'
  | 'employee'
  | 'manager'
  | 'auditor'
  | 'support'
  | 'merchant'
  | 'loan-officer'
  | 'investment'
  | 'insurance'
  | 'cryptocurrency'
  | 'payment-gateway'
  | 'fintech-partner';

export interface PersonaConfig {
  key: PersonaKey;
  label: string;
  icon: string;
  route: string;
  description: string;
  roles: BackendRole[];
  primaryAction: string;
  widgets: string[];
}
